// Central icon registry: flows/data reference icons by NAME (plain strings),
// the UI resolves them here. Explicit imports keep tree-shaking effective.
import { createElement } from 'react';
import {
  Activity,
  Apple,
  BarChart3,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  Compass,
  Cpu,
  Crosshair,
  Dna,
  ExternalLink,
  FileText,
  FileUp,
  FlaskConical,
  GaugeCircle,
  Globe2,
  GraduationCap,
  HeartPulse,
  Landmark,
  Languages,
  LayoutDashboard,
  Lightbulb,
  Lock,
  LogIn,
  Megaphone,
  MessageCircle,
  MessageCircleQuestion,
  MessagesSquare,
  Mic,
  Microscope,
  Palette,
  RotateCcw,
  Scale,
  Send,
  ShieldCheck,
  Smile,
  Sofa,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  Undo2,
  UserRound,
  Users,
  Wallet,
  X,
} from 'lucide-react';

export const ICONS = {
  Activity,
  Apple,
  BarChart3,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  Compass,
  Cpu,
  Crosshair,
  Dna,
  ExternalLink,
  FileText,
  FileUp,
  FlaskConical,
  GaugeCircle,
  Globe2,
  GraduationCap,
  HeartPulse,
  Landmark,
  Languages,
  LayoutDashboard,
  Lightbulb,
  Lock,
  LogIn,
  Megaphone,
  MessageCircle,
  MessageCircleQuestion,
  MessagesSquare,
  Mic,
  Microscope,
  Palette,
  RotateCcw,
  Scale,
  Send,
  ShieldCheck,
  Smile,
  Sofa,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  Undo2,
  UserRound,
  Users,
  Wallet,
  X,
};

/** Resolves an icon name to its component (Sparkles as a safe default). */
export function getIcon(name) {
  return ICONS[name] || Sparkles;
}

/**
 * Renders an icon by name. Use this inside JSX instead of assigning the
 * looked-up component to a local variable (keeps react-hooks/static-components
 * happy — the registry components are module-static, not created per render).
 */
export function renderIcon(name, props) {
  return createElement(getIcon(name), props);
}
